# Generated by Django 5.2.9 on 2025-12-23 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='Patient age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Patient gender', max_length=16)),
                ('symptoms', models.TextField(help_text='Patient-reported symptoms')),
                ('severity', models.PositiveSmallIntegerField(help_text='Pain severity on a scale of 1-10')),
                ('result', models.JSONField(help_text='AI-generated diagnosis result with conditions, summary, and recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this checkup (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkup',
                'verbose_name_plural': 'Checkups',
                'ordering': ['-created_at'],
            },
        ),
    ]
